# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Feelr < Formula
  desc "Agent-friendly API simplification layer CLI"
  homepage "https://feelr.dev"
  version "1.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/progradetech/homebrew-feelr/releases/download/v1.3.2/feelr_1.3.2_darwin_amd64.tar.gz"
      sha256 "0ec81729f8ecc206b331f9a7020f56e9be99d5236ba8cff2ca049e89aaa3e6d9"

      def install
        bin.install "feelr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/progradetech/homebrew-feelr/releases/download/v1.3.2/feelr_1.3.2_darwin_arm64.tar.gz"
      sha256 "bb2ababde44aaf8e20b213fbabce3bf5039e1fc0170c3c3aca998a7db788c9e3"

      def install
        bin.install "feelr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/progradetech/homebrew-feelr/releases/download/v1.3.2/feelr_1.3.2_linux_amd64.tar.gz"
      sha256 "0f906476f5c496bb3009791212f944826463bbfa8f8d6b7c6e79a10015e38284"
      def install
        bin.install "feelr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/progradetech/homebrew-feelr/releases/download/v1.3.2/feelr_1.3.2_linux_arm64.tar.gz"
      sha256 "a3e44af7ce0a20b10eef283524fa3564dd0efca801c5530c721f0d6517714fbe"
      def install
        bin.install "feelr"
      end
    end
  end
end
