# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Feelr < Formula
  desc "Agent-friendly API simplification layer CLI"
  homepage "https://feelr.dev"
  version "1.8.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/progradetech/feelr/releases/download/v1.8.3/feelr_1.8.3_darwin_amd64.tar.gz"
      sha256 "304a38fa4e0df15e6cc800b1237fc7078cae10e45dd27a8d0e706a5ebd3aeb66"

      define_method(:install) do
        bin.install "feelr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/progradetech/feelr/releases/download/v1.8.3/feelr_1.8.3_darwin_arm64.tar.gz"
      sha256 "cc3d3b25959c731ed51e88e9046772cc3bbaa6c2f78ff8d3bea8c00bfe9ac588"

      define_method(:install) do
        bin.install "feelr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/progradetech/feelr/releases/download/v1.8.3/feelr_1.8.3_linux_amd64.tar.gz"
      sha256 "fc1464d0b78623513bd82dab99cf320af99bbe5a12ef30f1ec3b0ce5fb76bb49"
      define_method(:install) do
        bin.install "feelr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/progradetech/feelr/releases/download/v1.8.3/feelr_1.8.3_linux_arm64.tar.gz"
      sha256 "2c4120a0903c7e37d6fe60f2b8ccbc07a727ace3d9ebf8e7bbd0c752de3d1fdd"
      define_method(:install) do
        bin.install "feelr"
      end
    end
  end
end
